"""abkit — A/B-testing and ranking-evaluation toolkit."""

from .data import DayAgg, ExperimentData, Issue, analyze, parse_csv_text, read_csv
from .ranking import (
    InterleavingResult,
    build_rankings,
    dcg,
    interleaving_outcome,
    interleaving_test,
    mean_ndcg_at_k,
    mrr,
    ndcg_at_k,
    precision_at_k,
    simulate_interleaving_sessions,
    team_draft_interleave,
    wilson_interval,
)
from .sequential import (
    SequentialResult,
    always_valid_p,
    mixture_likelihood_ratio,
    msprt_means,
    msprt_proportions,
    tau_from_mde,
)
from .stats import (
    CupedResult,
    CupedSumsResult,
    MeanStats,
    RelativeLiftResult,
    SRMResult,
    Sums,
    TTestResult,
    ZTestResult,
    bonferroni,
    cuped,
    cuped_from_sums,
    holm,
    mde_at_n,
    power_mean,
    power_proportion,
    ratio_metric_delta,
    relative_lift_ci,
    relative_lift_means,
    relative_lift_proportions,
    sample_size_mean,
    sample_size_proportion,
    srm_check,
    two_proportion_ztest,
    welch_ttest,
    welch_ttest_from_stats,
)

__version__ = "1.1.0"

__all__ = [
    "CupedResult",
    "CupedSumsResult",
    "DayAgg",
    "ExperimentData",
    "InterleavingResult",
    "Issue",
    "MeanStats",
    "RelativeLiftResult",
    "SRMResult",
    "SequentialResult",
    "Sums",
    "TTestResult",
    "ZTestResult",
    "always_valid_p",
    "analyze",
    "bonferroni",
    "build_rankings",
    "cuped",
    "cuped_from_sums",
    "dcg",
    "holm",
    "interleaving_outcome",
    "interleaving_test",
    "mde_at_n",
    "mean_ndcg_at_k",
    "mixture_likelihood_ratio",
    "mrr",
    "msprt_means",
    "msprt_proportions",
    "ndcg_at_k",
    "parse_csv_text",
    "power_mean",
    "power_proportion",
    "precision_at_k",
    "ratio_metric_delta",
    "read_csv",
    "relative_lift_ci",
    "relative_lift_means",
    "relative_lift_proportions",
    "sample_size_mean",
    "sample_size_proportion",
    "simulate_interleaving_sessions",
    "srm_check",
    "tau_from_mde",
    "team_draft_interleave",
    "two_proportion_ztest",
    "welch_ttest",
    "welch_ttest_from_stats",
    "wilson_interval",
]
