"""Tests for ``abkit.data``: CSV import (both layouts, RFC 4180, arm-label rules, skipped rows) and the end-to-end analysis.

The fixture files under ``tests/fixtures/csv`` are shared with the web app's importer; ``expected.json`` is the
cross-language parity reference (generated by ``make_fixtures.py``, asserted here and by the TypeScript tests).
"""
from __future__ import annotations

import importlib.util
import json
from io import BytesIO, StringIO
from pathlib import Path
from typing import Any

import numpy as np
import pytest
from scipy import stats as sps

from abkit import sequential, stats
from abkit.data import DayAgg, ExperimentData, Issue, analyze, parse_csv_text, read_csv

ROOT = Path(__file__).resolve().parents[1]
FIXTURES = ROOT / "tests" / "fixtures" / "csv"
FIXTURE_FILES = ["conversion_per_user.csv", "continuous_per_user_cuped.csv", "aggregated_daily.csv", "aggregated_continuous.csv", "semicolon_crlf_bom.csv", "three_variants_error.csv"]
ERROR_FIXTURE = "three_variants_error.csv"
REGENERATE = "run `python3 tests/fixtures/csv/make_fixtures.py` from the repository root"


def totals(d: ExperimentData) -> tuple[int, int, int, int]:
    return (d.n_a, d.n_b, d.conv_a, d.conv_b)


def assert_close(got: Any, want: Any, rel: float = 1e-12, path: str = "$") -> None:
    """Recursive comparison: exact for ints/strings/bools/None, relative tolerance for floats, same keys and lengths."""
    if isinstance(want, dict):
        assert isinstance(got, dict), path
        assert set(got) == set(want), f"{path}: keys {sorted(got)} != {sorted(want)}"
        for k in want:
            assert_close(got[k], want[k], rel, f"{path}.{k}")
    elif isinstance(want, list):
        assert isinstance(got, list) and len(got) == len(want), path
        for i, (g, w) in enumerate(zip(got, want, strict=True)):
            assert_close(g, w, rel, f"{path}[{i}]")
    elif isinstance(want, bool) or want is None or isinstance(want, str):
        assert got == want, f"{path}: {got!r} != {want!r}"
    elif isinstance(want, int) and not isinstance(got, float):
        assert got == want, f"{path}: {got!r} != {want!r}"
    else:
        assert isinstance(got, int | float), path
        assert got == pytest.approx(want, rel=rel, abs=1e-300), path


# --------------------------------------------------------------------------- RFC 4180 reader
def test_quoted_field_with_the_delimiter_stays_one_cell() -> None:
    d = parse_csv_text('variant,converted\nA,1\n"Variant, B",1\n"Variant, B",0\nA,0\n')
    assert d.fmt == "per-user" and d.metric_type == "conversion"
    assert d.labels == {"control": "A", "treatment": "Variant, B"}
    assert totals(d) == (2, 2, 1, 1)
    assert d.issues == () and d.rows == 4


def test_doubled_quotes_and_newlines_inside_quotes_and_physical_line_numbers() -> None:
    d = parse_csv_text('variant,converted\n"Ranker ""v2""",1\nA,0\n"Ranker ""v2""",0\n"A",1\n')
    assert d.treatment_label == 'Ranker "v2"'
    assert totals(d) == (2, 2, 1, 1)
    q = parse_csv_text('variant,converted\nA,1\n"Variant\nB",1\nA,oops\n"Variant\nB",0\n')
    assert q.treatment_label == "Variant\nB"
    assert [i.row for i in q.issues] == [5] and "converted" in q.issues[0].reason
    assert totals(q) == (1, 2, 1, 1)


def test_semicolon_crlf_bom_tab_and_decimal_comma() -> None:
    d = parse_csv_text("﻿variant;converted;day\r\nA;1;1\r\nB;0;1\r\nA;0;2\r\nB;1;2\r\n")
    assert d.issues == ()
    assert [x.day for x in d.days] == [1, 2]
    assert totals(d) == (2, 2, 1, 1)
    t = parse_csv_text("variant\tvalue\nA\t1.5\nB\t2.5\nA\t2.5\nB\t3.5\n")
    assert t.metric_type == "continuous" and not t.has_pre
    assert t.days[0].sums_a.sy == 4 and t.days[0].sums_b.sy == 6
    semi = parse_csv_text("variant;value\nA;12,5\nB;10,0\nA;7,5\nB;9\n")
    assert semi.days[0].sums_a.sy == 20 and semi.days[0].sums_b.sy == 19
    comma = parse_csv_text("variant,value\nA,1,5\nB,2\nA,1\nB,2\n")  # with a comma delimiter "1,5" is two cells → wrong width, skipped
    assert [i.row for i in comma.issues] == [2] and comma.rows == 3


def test_blank_lines_are_ignored_and_rows_with_the_wrong_width_are_skipped() -> None:
    d = parse_csv_text("variant,converted,day\nA,1,1\n\nB,1\nA,0,1\nB,0,1\n\n")
    assert d.issues == (Issue(4, "expected 3 columns, got 2"),)
    assert d.rows == 3 and totals(d) == (2, 1, 1, 0)


# --------------------------------------------------------------------------- per-user layout
def test_converted_accepts_boolean_words_and_reports_other_values() -> None:
    d = parse_csv_text("variant,converted\nA,true\nA,FALSE\nA,Yes\nA,no\nA,1\nA,0\nB,TRUE\nB,yes\nB,0\nA,maybe\n")
    assert totals(d) == (6, 3, 3, 2)
    assert [i.row for i in d.issues] == [11] and "maybe" in d.issues[0].reason
    assert d.rows == 9


def test_bad_numeric_cells_have_line_numbers_and_good_rows_are_kept() -> None:
    d = parse_csv_text("variant,value,pre_value,day\nA,10,9,1\nB,abc,9,1\nA,12,,1\nB,14,13,1\nB,11,10,x\nA,9,8,1\n")
    assert [i.row for i in d.issues] == [3, 4, 6]
    assert "value" in d.issues[0].reason and "pre_value" in d.issues[1].reason and "day" in d.issues[2].reason
    assert d.rows == 3 and d.has_pre and d.metric_type == "continuous"
    day = d.days[0]
    assert day.sums_a == stats.Sums(2, 17.0, 19.0, 145.0, 181.0, 162.0)
    assert day.sums_b == stats.Sums(1, 13.0, 14.0, 169.0, 196.0, 182.0)
    assert (day.n_a, day.n_b, day.conv_a, day.conv_b) == (2, 1, 0, 0)


def test_days_are_sorted_and_iso_dates_are_numbered_from_the_earliest() -> None:
    d = parse_csv_text("variant,converted,day\nA,1,3\nB,0,1\nA,0,2\nB,1,3\nA,1,1\nB,0,2\n")
    assert [x.day for x in d.days] == [1, 2, 3] and d.start_date is None
    e = parse_csv_text("variant,converted,day\nA,1,2026-09-03\nB,0,2026-09-01\nA,0,2026-09-02\nB,1,2026-09-03\n")
    assert [x.day for x in e.days] == [1, 2, 3] and e.start_date == "2026-09-01"
    assert e.days[2].n_a + e.days[2].n_b == 2
    with pytest.raises(ValueError, match="mixes"):
        parse_csv_text("variant,converted,day\nA,1,1\nB,0,2026-09-01\n")


# --------------------------------------------------------------------------- aggregated layout
def test_aggregated_conversion_layout() -> None:
    d = parse_csv_text("variant,users,conversions,day\nA,1000,100,1\nB,1000,120,1\nA,900,80,2\nB,950,99,2\n")
    assert d.fmt == "aggregated" and d.metric_type == "conversion" and d.rows == 4 and not d.has_pre
    empty = stats.Sums.empty()
    assert d.days == (DayAgg(1, 1000, 1000, 100, 120, empty, empty), DayAgg(2, 900, 950, 80, 99, empty, empty))
    s = parse_csv_text("variant,users,conversions\nA,1000,100\nA,500,40\nB,1500,160\nB,10,12\nA,-5,0\n")
    assert len(s.days) == 1 and (s.days[0].n_a, s.days[0].n_b, s.days[0].conv_a, s.days[0].conv_b) == (1500, 1500, 140, 160)
    assert [(i.row, i.reason.split(" ")[0]) for i in s.issues] == [(5, "conversions"), (6, "users")]


def test_aggregated_continuous_layout_reads_sums() -> None:
    d = parse_csv_text("variant,users,sum,sum_sq,pre_sum,pre_sum_sq,cross_sum,day\nA,3,30,320,27,251,275,1\nB,3,36,450,30,310,370,1\n")
    assert d.fmt == "aggregated" and d.has_pre and d.metric_type == "continuous"
    assert d.days[0].sums_a == stats.Sums(3, 27, 30, 251, 320, 275)
    assert d.days[0].sums_b == stats.Sums(3, 30, 36, 310, 450, 370)
    assert (d.days[0].n_a, d.days[0].n_b, d.days[0].conv_a, d.days[0].conv_b) == (3, 3, 0, 0)
    plain = parse_csv_text("variant,users,sum,sum_sq\nA,4,40,420\nB,4,44,500\nB,2,20,150\n")
    assert not plain.has_pre
    assert plain.days[0].sums_a == stats.Sums(4, 0, 40, 0, 420, 0)
    assert [i.row for i in plain.issues] == [4] and "sum_sq" in plain.issues[0].reason
    with pytest.raises(ValueError, match="pre_sum_sq"):
        parse_csv_text("variant,users,sum,sum_sq,pre_sum\nA,4,40,420,1\nB,4,44,500,2\n")


# --------------------------------------------------------------------------- labels and errors
def test_standard_labels_are_case_insensitive_and_mixed_spellings_warn() -> None:
    d = parse_csv_text("variant,converted\ncontrol,1\nTreatment,0\nCTRL,0\nTEST,1\nbaseline,1\n1,1\n0,0\nvariant,1\n")
    assert d.labels == {"control": "control", "treatment": "Treatment"}
    assert totals(d) == (4, 4, 2, 3)
    assert len(d.warnings) == 2
    assert "control, CTRL, baseline, 0" in d.warnings[0] and "Treatment, TEST, 1, variant" in d.warnings[1]
    plain = parse_csv_text("variant,converted\nA,1\nb,0\na,0\nB,1\n")
    assert plain.labels == {"control": "A", "treatment": "b"} and plain.warnings == ()


def test_unknown_label_pair_takes_the_first_seen_as_control_unless_named() -> None:
    text = "variant,converted\nnew,1\nold,0\nold,1\nnew,0\n"
    d = parse_csv_text(text)
    assert d.labels == {"control": "new", "treatment": "old"}
    assert any('"new"' in w and "control" in w for w in d.warnings)
    o = parse_csv_text(text, control_label="OLD")
    assert o.labels == {"control": "old", "treatment": "new"} and o.warnings == ()
    assert totals(o) == (2, 2, 1, 1)
    with pytest.raises(ValueError, match=r"zzz.*new.*old"):
        parse_csv_text(text, control_label="zzz")
    same = parse_csv_text("variant,converted\na,1\ncontrol,0\n")
    assert same.labels == {"control": "a", "treatment": "control"} and len(same.warnings) == 1


def test_three_labels_or_a_single_label_is_an_error_listing_them() -> None:
    with pytest.raises(ValueError, match="A, B, C"):
        parse_csv_text("variant,converted\nA,1\nB,0\nC,1\n")
    with pytest.raises(ValueError, match="both arms"):
        parse_csv_text("variant,converted\nA,1\nA,0\n")


def test_header_and_empty_input_errors_are_actionable() -> None:
    with pytest.raises(ValueError, match="variant"):
        parse_csv_text("foo,bar\n1,2\n")
    with pytest.raises(ValueError, match="conversions|sum"):
        parse_csv_text("variant,users\nA,10\nB,10\n")
    with pytest.raises(ValueError, match="data row"):
        parse_csv_text("variant,converted\n")
    with pytest.raises(ValueError, match="data row"):
        parse_csv_text("")
    with pytest.raises(ValueError, match="usable"):
        parse_csv_text("variant,value\nA,x\nB,y\n")


def test_read_csv_accepts_paths_and_text_or_binary_file_objects(tmp_path: Path) -> None:
    text = "variant,converted,day\nA,1,1\nB,0,1\nA,0,2\nB,1,2\n"
    path = tmp_path / "x.csv"
    path.write_text("﻿" + text, encoding="utf-8")
    ref = parse_csv_text(text)
    assert ref.rows == 4
    assert read_csv(path) == ref
    assert read_csv(str(path)) == ref
    assert read_csv(StringIO(text)) == ref
    assert read_csv(BytesIO(("﻿" + text).encode("utf-8"))) == ref
    with path.open("rb") as fh:
        assert read_csv(fh) == ref
    with pytest.raises(ValueError):
        read_csv(path, control_label="C")


# --------------------------------------------------------------------------- analysis
def _conversion_text(conv_b: list[int]) -> str:
    rows = ["variant,users,conversions,day"]
    for day, (ca, cb) in enumerate(zip([100, 97, 104, 99], conv_b, strict=True), start=1):
        rows += [f"A,1000,{ca},{day}", f"B,1000,{cb},{day}"]
    return "\n".join(rows) + "\n"


def test_analyze_conversion_matches_the_component_statistics() -> None:
    r = analyze(parse_csv_text(_conversion_text([112, 118, 125, 121])))
    assert r["metric_type"] == "conversion" and r["format"] == "aggregated" and r["days"] == 4
    assert (r["n_a"], r["n_b"], r["conv_a"], r["conv_b"]) == (4000, 4000, 400, 476)
    z = stats.two_proportion_ztest(400, 4000, 476, 4000)
    assert r["test"]["kind"] == "two_proportion_z"
    assert r["test"]["statistic"] == z.z and r["test"]["p_value"] == z.p_value
    assert r["test"]["p_value"] == pytest.approx(2 * sps.norm.sf(abs(z.z)))
    assert (r["test"]["ci_low"], r["test"]["ci_high"]) == (z.ci_low, z.ci_high)
    assert r["relative_lift"] == stats.relative_lift_proportions(400, 4000, 476, 4000).as_dict()
    srm = stats.srm_check([4000, 4000], [0.5, 0.5])
    assert r["srm"] == {"chi2": srm.chi2, "p_value": srm.p_value, "mismatch": False, "expected": [4000.0, 4000.0]}
    seq = sequential.msprt_proportions([100, 197, 301, 400], [1000, 2000, 3000, 4000], [112, 230, 355, 476], [1000, 2000, 3000, 4000], tau=0.1 * 0.05)
    assert r["sequential"]["tau"] == 0.1 * 0.05
    assert r["sequential"]["always_valid_p"] == list(seq.always_valid_p)
    assert r["sequential"]["decided_day"] == seq.decided_at
    assert [p["day"] for p in r["series"]] == [1, 2, 3, 4]
    assert [p["n"] for p in r["series"]] == [2000, 4000, 6000, 8000]
    assert [p["always_valid_p"] for p in r["series"]] == list(seq.always_valid_p)
    last = r["series"][-1]
    assert last["p_value"] == z.p_value and last["lift_rel"] == r["relative_lift"]["lift_rel"]
    assert (last["ci_low"], last["ci_high"]) == (r["relative_lift"]["ci_low"], r["relative_lift"]["ci_high"])
    first = stats.two_proportion_ztest(100, 1000, 112, 1000)
    assert r["series"][0]["p_value"] == first.p_value
    assert r["cuped"] is None
    assert r["verdict"] == {"decision": "winner", "basis": "fixed", "reason": r["verdict"]["reason"]}
    assert r["progress"] == 1.0 and r["planned_per_arm"] is None
    assert r["labels"] == {"control": "A", "treatment": "B"} and r["rows"] == 8 and r["skipped"] == [] and r["warnings"] == []
    json.dumps(r, allow_nan=False)


def test_analyze_verdict_rules_and_options() -> None:
    small = parse_csv_text(_conversion_text([112, 118, 125, 121]))
    r = analyze(small, planned_per_arm=10_000)
    assert r["progress"] == pytest.approx(0.4) and r["planned_per_arm"] == 10_000
    assert r["verdict"]["decision"] == "collecting" and r["verdict"]["basis"] == "fixed"
    big = parse_csv_text(_conversion_text([150, 148, 155, 152]))
    r = analyze(big, planned_per_arm=10_000)
    assert r["sequential"]["always_valid_p"][-1] < 0.05 and r["sequential"]["decided_day"] is not None
    assert r["verdict"]["decision"] == "winner" and r["verdict"]["basis"] == "sequential"
    assert str(r["sequential"]["decided_day"]) in r["verdict"]["reason"]
    loser = parse_csv_text(_conversion_text([60, 58, 55, 62]))
    assert analyze(loser)["verdict"] | {"reason": ""} == {"decision": "loser", "basis": "fixed", "reason": ""}
    flat = parse_csv_text(_conversion_text([101, 96, 105, 98]))
    assert analyze(flat)["verdict"]["decision"] == "flat"
    skew = parse_csv_text("variant,users,conversions\nA,4000,400\nB,4800,480\n")
    r = analyze(skew)
    assert r["srm"]["mismatch"] is True and r["srm"]["p_value"] < 1e-6
    assert r["verdict"] | {"reason": ""} == {"decision": "invalid", "basis": "fixed", "reason": ""}
    assert analyze(skew, split=4000 / 8800)["srm"]["mismatch"] is False
    strict = analyze(small, alpha=0.01)
    assert strict["test"]["ci_low"] < analyze(small)["test"]["ci_low"] and strict["alpha"] == 0.01  # wider interval at a stricter alpha
    assert analyze(small, mde_rel=0.1)["sequential"]["tau"] == pytest.approx(0.1 * 0.1)
    with pytest.raises(ValueError):
        analyze(small, alpha=0.0)
    with pytest.raises(ValueError):
        analyze(small, alpha=1.0)
    with pytest.raises(ValueError):
        analyze(small, split=1.0)
    with pytest.raises(ValueError):
        analyze(small, mde_rel=0.0)
    with pytest.raises(ValueError):
        analyze(small, planned_per_arm=-1)


def _continuous_text(with_pre: bool, seed: int = 1) -> tuple[str, dict[str, tuple[np.ndarray, np.ndarray]]]:
    rng = np.random.default_rng(seed)
    rows = ["variant,value,pre_value,day" if with_pre else "variant,value,day"]
    arms: dict[str, tuple[np.ndarray, np.ndarray]] = {}
    for label, mean in (("control", 100.0), ("treatment", 103.0)):
        z1, z2 = rng.standard_normal(800), rng.standard_normal(800)
        pre = np.round(100 + 30 * z1, 4)
        val = np.round(mean + 40 * (0.6 * z1 + 0.8 * z2), 4)
        arms[label] = (pre, val)
        for i in range(800):
            day = 1 if i < 400 else 2
            rows.append(f"{label},{float(val[i]):.4f},{float(pre[i]):.4f},{day}" if with_pre else f"{label},{float(val[i]):.4f},{day}")
    return "\n".join(rows) + "\n", arms


def test_analyze_continuous_with_and_without_cuped() -> None:
    text, arms = _continuous_text(True)
    data = parse_csv_text(text)
    assert data.metric_type == "continuous" and data.has_pre and len(data.days) == 2 and data.rows == 1600
    r = analyze(data)
    last = data.cumulative()[-1]
    a, b = last.sums_a.mean_var(), last.sums_b.mean_var()
    raw = stats.welch_ttest_from_stats(a, b)
    assert r["test"]["kind"] == "welch_t"
    assert (r["test"]["statistic"], r["test"]["df"], r["test"]["p_value"]) == (raw.t, raw.df, raw.p_value)
    assert (r["test"]["mean_a"], r["test"]["mean_b"], r["test"]["ci_low"], r["test"]["ci_high"]) == (raw.mean_a, raw.mean_b, raw.ci_low, raw.ci_high)
    ref = sps.ttest_ind(arms["treatment"][1], arms["control"][1], equal_var=False)
    assert r["test"]["p_value"] == pytest.approx(ref.pvalue, rel=1e-9)
    c = stats.cuped_from_sums(last.sums_a, last.sums_b)
    adj = stats.welch_ttest_from_stats(c.adj_a, c.adj_b)
    cu = r["cuped"]
    assert cu is not None and cu["theta"] == c.theta and cu["variance_reduction"] == c.variance_reduction
    assert cu["variance_reduction"] > 0.2
    assert cu["adjusted_test"]["p_value"] == adj.p_value and cu["adjusted_test"]["kind"] == "welch_t"
    assert r["relative_lift"] == stats.relative_lift_means(c.adj_a, c.adj_b).as_dict()
    assert r["relative_lift_raw"] == stats.relative_lift_means(a, b).as_dict()
    assert r["sequential"]["tau"] == abs(a.mean * 0.05)
    looks_a, looks_b = [], []
    for d in data.cumulative():
        ck = stats.cuped_from_sums(d.sums_a, d.sums_b)
        looks_a.append(ck.adj_a)
        looks_b.append(ck.adj_b)
    seq = sequential.msprt_means(looks_a, looks_b, tau=abs(a.mean * 0.05))
    assert r["sequential"]["always_valid_p"] == list(seq.always_valid_p)
    assert r["sequential"]["decided_day"] == (data.days[seq.decided_at - 1].day if seq.decided_at else None)
    s = r["series"][-1]
    assert s["p_value"] == adj.p_value and s["p_value_raw"] == raw.p_value
    assert (s["lift_rel"], s["ci_low"], s["ci_high"]) == (r["relative_lift"]["lift_rel"], r["relative_lift"]["ci_low"], r["relative_lift"]["ci_high"])
    assert (s["ci_low_raw"], s["ci_high_raw"]) == (r["relative_lift_raw"]["ci_low"], r["relative_lift_raw"]["ci_high"])
    assert (r["conv_a"], r["conv_b"]) == (0, 0) and r["has_pre"] is True
    json.dumps(r, allow_nan=False)

    plain, _ = _continuous_text(False)
    r2 = analyze(parse_csv_text(plain))
    assert r2["cuped"] is None and r2["has_pre"] is False
    assert r2["test"]["p_value"] == raw.p_value
    assert r2["relative_lift"] == stats.relative_lift_means(a, b).as_dict()
    assert r2["series"][-1]["p_value"] == raw.p_value


def test_analyze_rejects_data_that_cannot_be_analysed() -> None:
    with pytest.raises(ValueError, match="two users"):
        analyze(parse_csv_text("variant,value\nA,1\nB,2\n"))


# --------------------------------------------------------------------------- fixtures and parity reference
@pytest.mark.parametrize("name", FIXTURE_FILES)
def test_fixture_file_exists_and_is_small(name: str) -> None:
    path = FIXTURES / name
    assert path.is_file(), f"missing fixture {name} — {REGENERATE}"
    assert path.stat().st_size <= 200 * 1024


def test_fixtures_have_the_documented_shapes() -> None:
    conv = read_csv(FIXTURES / "conversion_per_user.csv")
    assert conv.fmt == "per-user" and conv.metric_type == "conversion" and len(conv.days) == 7
    assert conv.labels == {"control": "A", "treatment": "B"} and 3_500 <= conv.rows <= 4_500 and conv.issues == ()
    cont = read_csv(FIXTURES / "continuous_per_user_cuped.csv")
    assert cont.fmt == "per-user" and cont.metric_type == "continuous" and cont.has_pre and len(cont.days) == 10
    assert cont.start_date == "2026-09-01" and cont.labels == {"control": "control", "treatment": "treatment"} and 2_700 <= cont.rows <= 3_300
    agg = read_csv(FIXTURES / "aggregated_daily.csv")
    assert agg.fmt == "aggregated" and agg.metric_type == "conversion" and len(agg.days) == 14 and agg.rows == 28
    assert analyze(agg)["srm"]["mismatch"] is True
    aggc = read_csv(FIXTURES / "aggregated_continuous.csv")
    assert aggc.fmt == "aggregated" and aggc.metric_type == "continuous" and aggc.has_pre and len(aggc.days) == 10
    semi = read_csv(FIXTURES / "semicolon_crlf_bom.csv")
    assert semi.labels == {"control": "old", "treatment": "new"} and len(semi.warnings) == 1 and len(semi.days) == 5
    assert [i.row for i in semi.issues] and len(semi.issues) >= 3
    raw = (FIXTURES / "semicolon_crlf_bom.csv").read_bytes()
    assert raw.startswith(b"\xef\xbb\xbf") and b"\r\n" in raw and b";" in raw
    with pytest.raises(ValueError, match="A, B, C"):
        read_csv(FIXTURES / ERROR_FIXTURE)


def test_expected_json_matches_analyze_for_every_fixture() -> None:
    path = FIXTURES / "expected.json"
    assert path.is_file(), f"missing expected.json — {REGENERATE}"
    expected = json.loads(path.read_text(encoding="utf-8"))
    assert set(expected) == set(FIXTURE_FILES)
    for name in FIXTURE_FILES:
        if name == ERROR_FIXTURE:
            with pytest.raises(ValueError) as exc:
                read_csv(FIXTURES / name)
            assert expected[name] == {"error": str(exc.value)}
            continue
        got = analyze(read_csv(FIXTURES / name))
        assert_close(got, expected[name])
        assert {"metric_type", "format", "days", "n_a", "n_b", "conv_a", "conv_b", "srm", "test", "relative_lift", "cuped", "sequential", "series", "verdict"} <= set(got)


def test_make_fixtures_regenerates_identical_files(tmp_path: Path) -> None:
    spec = importlib.util.spec_from_file_location("make_fixtures", FIXTURES / "make_fixtures.py")
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    module.build(tmp_path)
    for name in FIXTURE_FILES:
        assert (tmp_path / name).read_bytes() == (FIXTURES / name).read_bytes(), f"{name} differs — {REGENERATE}"
    regenerated = json.loads((tmp_path / "expected.json").read_text(encoding="utf-8"))
    committed = json.loads((FIXTURES / "expected.json").read_text(encoding="utf-8"))
    assert_close(regenerated, committed)
