/**
 * Parity tests for the interleaving library against tests/fixtures/ranking.json. The fixture is generated by
 * `python3 tests/test_ranking.py` from SciPy (binomtest, norm.ppf, lgamma) and the Python implementation of the same
 * ranking/simulation model, so these tests pin the TypeScript twin to the Python package.
 */
import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { mrr, mulberry32, ndcgAtK, precisionAtK, twoProportionZ } from "../stats";
import { binomialTwoSidedP, buildRankings, interleavingTest, logChoose, meanNdcgAtK, normalQuantile, parseGrades, simulateSessions, wilson } from "./interleaving";

interface PyResult { wins_a: number; wins_b: number; ties: number; p_value: number; preference: number; ci_low: number; ci_high: number; winner: string; alpha: number }
interface Fixture {
  binomial_two_sided: Record<string, number>;
  binomial_two_sided_large: Record<string, number>;
  log_choose: Record<string, number>;
  norm_ppf: Record<string, number>;
  wilson: Record<string, [number, number]>;
  interleaving: { wins_a: number; wins_b: number; ties: number; alpha: number; result: PyResult }[];
  rankings: { rel_a: number[]; rel_b: number[]; grades: number[]; order_a: number[]; order_b: number[] }[];
  offline: {
    ndcg: { rels: number[]; k: number; value: number }[];
    mrr: { flags: boolean[][]; value: number }[];
    precision: { flags: boolean[]; k: number; value: number }[];
    mean_ndcg: { queries: number[][]; k: number; value: number }[];
  };
  wrong_ztest_p_100_120: number;
}

const fx = JSON.parse(readFileSync(new URL("../../../tests/fixtures/ranking.json", import.meta.url), "utf8")) as Fixture;
const REL = 1e-12;
const A = [3, 2, 3, 0, 1, 2, 0, 0, 1, 0];
const B = [3, 3, 2, 2, 1, 0, 1, 0, 0, 0];

/** Asserts |got − want| ≤ rel·|want| + abs. Without an absolute tolerance, an exact zero in the fixture must be reproduced exactly. */
function expectClose(got: number, want: number, label: string, rel = REL, abs = 0): void {
  if (want === 0 && abs === 0) {
    expect(got, label).toBe(0);
    return;
  }
  expect(Number.isFinite(got), `${label}: got ${got}`).toBe(true);
  expect(Math.abs(got - want), `${label}: got ${got}, want ${want}`).toBeLessThanOrEqual(rel * Math.abs(want) + abs);
}
const nums = (key: string): number[] => key.split("/").map(Number);

describe("binomialTwoSidedP (exact two-sided binomial test, p0 = 1/2)", () => {
  it("matches scipy.stats.binomtest(k, n, 0.5).pvalue to 1e-12 across the fixture table", () => {
    const keys = Object.keys(fx.binomial_two_sided);
    expect(keys.length).toBeGreaterThanOrEqual(300);
    for (const key of keys) {
      const [k = NaN, n = NaN] = nums(key);
      expectClose(binomialTwoSidedP(k, n), fx.binomial_two_sided[key]!, `binomial ${key}`);
    }
    expectClose(binomialTwoSidedP(120, 220), 0.2000922290282712, "120/220");
    expect(binomialTwoSidedP(0, 0)).toBe(1);
    expect(binomialTwoSidedP(5, 10)).toBe(1);
    expect(binomialTwoSidedP(3, 7)).toBe(1);
  });

  it("is the correctly rounded exact value for every k ≤ n ≤ 52 (independent Pascal-triangle oracle)", () => {
    let row: bigint[] = [1n];
    for (let n = 0; n <= 52; n++) {
      if (n > 0) row = Array.from({ length: n + 1 }, (_, i) => (row[i - 1] ?? 0n) + (row[i] ?? 0n));
      const prefix: bigint[] = [];
      let acc = 0n;
      for (const c of row) { acc += c; prefix.push(acc); }
      for (let k = 0; k <= n; k++) {
        const m = Math.min(k, n - k);
        const want = 2 * m === n ? 1 : Number(2n * prefix[m]!) / 2 ** n; // 2·Σ C(n,i) < 2^53 here, so this is exact
        expect(binomialTwoSidedP(k, n), `${k}/${n}`).toBe(want);
      }
    }
  });

  it("documents the defect: the lab's old two-proportion z-test on complementary shares overstated significance", () => {
    const old = twoProportionZ(100, 220, 120, 220).p;
    expect(Math.abs(old - fx.wrong_ztest_p_100_120)).toBeLessThan(1e-5);
    const exact = interleavingTest(100, 120).pValue;
    expectClose(exact, 0.2000922290282712, "exact p for 100 vs 120 wins");
    expect(exact).toBeGreaterThan(0.1);
    expect(Math.abs(exact - old)).toBeGreaterThan(0.1);
  });

  it("uses a log-gamma recurrence beyond the exact range and stays within 1e-9 of SciPy; logChoose is accurate to 1e-12", () => {
    const large = Object.entries(fx.binomial_two_sided_large);
    expect(large.length).toBeGreaterThanOrEqual(5);
    for (const [key, want] of large) {
      const [k = NaN, n = NaN] = nums(key);
      expectClose(binomialTwoSidedP(k, n), want, `large binomial ${key}`, 1e-9);
    }
    for (const [key, want] of Object.entries(fx.log_choose)) {
      const [n = NaN, k = NaN] = nums(key);
      expectClose(logChoose(n, k), want, `logChoose ${key}`, REL, 1e-13);
    }
    expect(logChoose(30, 0)).toBe(0);
    expectClose(logChoose(5, 2), Math.log(10), "logChoose 5/2", 1e-14);
  });

  it("rejects invalid inputs", () => {
    expect(() => binomialTwoSidedP(-1, 3)).toThrow();
    expect(() => binomialTwoSidedP(4, 3)).toThrow();
    expect(() => binomialTwoSidedP(1.5, 3)).toThrow();
    expect(() => binomialTwoSidedP(1, NaN)).toThrow();
    expect(() => logChoose(3, 4)).toThrow();
  });
});

describe("normalQuantile and wilson", () => {
  it("normalQuantile matches scipy.stats.norm.ppf to 1e-12", () => {
    const entries = Object.entries(fx.norm_ppf);
    expect(entries.length).toBeGreaterThanOrEqual(10);
    for (const [key, want] of entries) expectClose(normalQuantile(Number(key)), want, `ppf ${key}`, REL, 1e-14);
    expect(Number.isNaN(normalQuantile(0))).toBe(true);
    expect(Number.isNaN(normalQuantile(1))).toBe(true);
    expect(normalQuantile(0.5)).toBe(0);
  });

  it("wilson matches the Python fixture, never leaves [0, 1] and widens for a smaller alpha", () => {
    for (const [key, want] of Object.entries(fx.wilson)) {
      const [k = NaN, n = NaN, alpha = NaN] = nums(key);
      const [lo, hi] = wilson(k, n, alpha);
      expectClose(lo, want[0], `wilson lo ${key}`, REL, 1e-14);
      expectClose(hi, want[1], `wilson hi ${key}`, REL, 1e-14);
    }
    expect(wilson(0, 0)).toEqual([0, 1]);
    expect(wilson(0, 10)[0]).toBeLessThanOrEqual(1e-14);
    expect(wilson(10, 10)[1]).toBeGreaterThanOrEqual(1 - 1e-14);
    const [n05lo, n05hi] = wilson(500, 1000);
    const [n01lo, n01hi] = wilson(500, 1000, 0.01);
    expect(n01lo).toBeLessThan(n05lo);
    expect(n05lo).toBeLessThan(0.5);
    expect(n05hi).toBeLessThan(n01hi);
    expect(() => wilson(5, 3)).toThrow();
    expect(() => wilson(1, 3, 0)).toThrow();
  });
});

describe("interleavingTest", () => {
  it("reproduces every Python result: exact p, preference, Wilson CI mapped by 2p − 1 and the winner", () => {
    expect(fx.interleaving.length).toBeGreaterThanOrEqual(10);
    for (const c of fx.interleaving) {
      const label = `${c.wins_a}/${c.wins_b}/${c.ties}/${c.alpha}`;
      const r = interleavingTest(c.wins_a, c.wins_b, c.ties, c.alpha);
      expect([r.winsA, r.winsB, r.ties, r.alpha, r.decided], label).toEqual([c.wins_a, c.wins_b, c.ties, c.alpha, c.wins_a + c.wins_b]);
      expectClose(r.pValue, c.result.p_value, `${label} p`);
      expectClose(r.preference, c.result.preference, `${label} preference`, REL, 1e-14);
      expectClose(r.ciLow, c.result.ci_low, `${label} ciLow`, REL, 1e-14);
      expectClose(r.ciHigh, c.result.ci_high, `${label} ciHigh`, REL, 1e-14);
      expect(r.winner, label).toBe(c.result.winner);
      expect(r.ciLow).toBeLessThanOrEqual(r.preference);
      expect(r.preference).toBeLessThanOrEqual(r.ciHigh);
    }
  });

  it("handles the no-decided-sessions case, applies defaults and validates input", () => {
    const none = interleavingTest(0, 0, 7);
    expect(none).toMatchObject({ winsA: 0, winsB: 0, ties: 7, decided: 0, pValue: 1, preference: 0, ciLow: -1, ciHigh: 1, winner: "tie", alpha: 0.05 });
    const r = interleavingTest(100, 150);
    expect(r.ties).toBe(0);
    expect(r.alpha).toBe(0.05);
    expect(r.winner).toBe("B");
    expect(interleavingTest(150, 100).winner).toBe("A");
    expect(interleavingTest(100, 120, 0, 0.25).winner).toBe("B");
    expect(() => interleavingTest(-1, 2)).toThrow();
    expect(() => interleavingTest(1.5, 2)).toThrow();
    expect(() => interleavingTest(1, 2, -1)).toThrow();
    expect(() => interleavingTest(1, 2, 0, 0)).toThrow();
    expect(() => interleavingTest(1, 2, 0, 1)).toThrow();
  });
});

describe("rankings, offline metrics and the session simulator", () => {
  it("buildRankings matches the Python shared-pool model exactly", () => {
    expect(fx.rankings.length).toBeGreaterThanOrEqual(4);
    for (const c of fx.rankings) {
      expect(buildRankings(c.rel_a, c.rel_b), JSON.stringify([c.rel_a, c.rel_b])).toEqual({ grades: c.grades, orderA: c.order_a, orderB: c.order_b });
    }
    expect(buildRankings([], [])).toEqual({ grades: [], orderA: [], orderB: [] });
    expect(buildRankings([3, 2], [1])).toEqual({ grades: [3, 2], orderA: [0, 1], orderB: [1, 0] });
    expect(() => buildRankings([4], [0])).toThrow();
    expect(() => buildRankings([1], [-1])).toThrow();
    expect(() => buildRankings([1.5], [0])).toThrow();
  });

  it("offline metrics agree with the Python fixture", () => {
    for (const c of fx.offline.ndcg) expectClose(ndcgAtK(c.rels, c.k), c.value, `ndcg ${JSON.stringify(c.rels)}@${c.k}`, 1e-12, 1e-15);
    for (const c of fx.offline.mrr) expectClose(mrr(c.flags), c.value, `mrr ${JSON.stringify(c.flags)}`, 1e-12, 1e-15);
    for (const c of fx.offline.precision) expectClose(precisionAtK(c.flags, c.k), c.value, `precision ${JSON.stringify(c.flags)}@${c.k}`, 1e-12, 1e-15);
    for (const c of fx.offline.mean_ndcg) expectClose(meanNdcgAtK(c.queries, c.k), c.value, `meanNdcg @${c.k}`, 1e-12, 1e-15);
    expect(meanNdcgAtK([], 3)).toBe(0);
    expect(() => meanNdcgAtK([[1, 0]], 0)).toThrow();
  });

  it("simulateSessions is deterministic, conserves sessions, is fair for identical rankers and decisive when B leads", () => {
    const first = simulateSessions(A, B, 400, mulberry32(7));
    expect(simulateSessions(A, B, 400, mulberry32(7))).toEqual(first);
    expect(first.winsA + first.winsB + first.ties).toBe(400);
    expect(Math.min(first.winsA, first.winsB, first.ties)).toBeGreaterThanOrEqual(0);
    expect(simulateSessions(A, B, 0, mulberry32(1))).toEqual({ winsA: 0, winsB: 0, ties: 0 });
    const same = simulateSessions(A, A, 2000, mulberry32(3));
    expect(interleavingTest(same.winsA, same.winsB).pValue).toBeGreaterThan(0.01);
    const decisive = simulateSessions([0, 0, 0, 0, 3, 3, 3, 3], [3, 3, 3, 3, 0, 0, 0, 0], 400, mulberry32(5));
    expect(decisive.winsA).toBe(0);
    expect(decisive.winsB).toBeGreaterThan(300);
    expect(interleavingTest(decisive.winsA, decisive.winsB, decisive.ties).winner).toBe("B");
    expect(simulateSessions(A, B, 50, mulberry32(1), 0)).toEqual({ winsA: 0, winsB: 0, ties: 50 });
    expect(() => simulateSessions(A, B, -1, mulberry32(1))).toThrow();
    expect(() => simulateSessions(A, B, 10, mulberry32(1), 1.5)).toThrow();
  });

  it("parseGrades clamps to 0–3, rounds, ignores junk and keeps at most 20 positions", () => {
    expect(parseGrades("3, 2,x,5,-1,1.6")).toEqual([3, 2, 3, 0, 2]);
    expect(parseGrades("1 2\t3")).toEqual([1, 2, 3]);
    expect(parseGrades("")).toEqual([]);
    expect(parseGrades(" , ")).toEqual([]);
    expect(parseGrades(Array.from({ length: 25 }, () => "1").join(","))).toHaveLength(20);
    expect(parseGrades("1,2,3,0,1", 3)).toEqual([1, 2, 3]);
  });
});
