import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { binomial, mulberry32, normPpf } from "../stats";
import { alwaysValidP, meanPoint, mixtureLR, msprtSeries, proportionPoint, tauFromMde, type SeqPoint } from "./sequential";

// Parity fixture generated by the Python implementation: `python3 tests/test_sequential.py` (repo root).
interface MeanStatsRow { n: number; mean: number; var: number }
interface Expected { tau: number; alpha: number; lr: number[]; always_valid_p: number[]; decided_at: number | null }
interface Fixture {
  lr_cases: { diff: number; var_diff: number; tau: number; lr: number }[];
  always_valid_p_cases: { lrs: number[]; p: number[] }[];
  tau_cases: { mde_abs: number; tau: number }[];
  proportion_cases: { name: string; conv_a: number[]; n_a: number[]; conv_b: number[]; n_b: number[]; tau: number | null; alpha: number; mde_rel: number | null; expected: Expected }[];
  mean_cases: { name: string; a: MeanStatsRow[]; b: MeanStatsRow[]; tau: number; alpha: number; expected: Expected }[];
}

const fixture = JSON.parse(readFileSync(new URL("../../../tests/fixtures/sequential.json", import.meta.url), "utf8")) as Fixture;
const REL = 1e-12;

/** |actual − expected| ≤ 1e-12 · max(|actual|, |expected|); zero must be matched exactly, NaN never passes. */
function expectClose(actual: number, expected: number, what: string): void {
  const tol = REL * Math.max(Math.abs(actual), Math.abs(expected));
  expect(Math.abs(actual - expected), `${what}: got ${actual}, expected ${expected}`).toBeLessThanOrEqual(tol);
}

function expectSeries(actual: { lr: number[]; pAV: number[]; decidedAt: number | null }, expected: Expected, name: string): void {
  expect(actual.lr.length, `${name}: lr length`).toBe(expected.lr.length);
  expect(actual.pAV.length, `${name}: pAV length`).toBe(expected.always_valid_p.length);
  expected.lr.forEach((v, k) => expectClose(actual.lr[k]!, v, `${name}: lr[${k}]`));
  expected.always_valid_p.forEach((v, k) => expectClose(actual.pAV[k]!, v, `${name}: pAV[${k}]`));
  expect(actual.decidedAt, `${name}: decidedAt`).toBe(expected.decided_at);
}

describe("mixtureLR", () => {
  it("matches the hand calculation and the closed form; is two-sided", () => {
    const diff = 0.004, v = 1.8e-6, tau = 0.01;
    const lr = mixtureLR(diff, v, tau);
    expectClose(lr, 10.467207377136294, "hand calculation");
    expectClose(lr, Math.sqrt(v / (v + tau * tau)) * Math.exp((diff * diff * tau * tau) / (2 * v * (v + tau * tau))), "closed form");
    expect(mixtureLR(-diff, v, tau)).toBe(lr);
    expectClose(mixtureLR(0, v, tau), Math.sqrt(v / (v + tau * tau)), "no difference");
    expect(mixtureLR(0, v, tau)).toBeLessThan(1); // no observed difference is mild evidence for H0
  });

  it("handles the degenerate variance limit, overflow and bad input", () => {
    expect(mixtureLR(0, 0, 0.01)).toBe(0);
    expect(mixtureLR(1e-9, 0, 0.01)).toBe(Infinity);
    expect(mixtureLR(0.5, 1e-9, 0.01)).toBe(Infinity); // overwhelming evidence overflows exp(): +Infinity, not NaN
    expect(() => mixtureLR(0.1, -1e-6, 0.01)).toThrow();
    expect(() => mixtureLR(0.1, 1e-6, 0)).toThrow();
    expect(() => mixtureLR(0.1, 1e-6, -0.01)).toThrow();
    expect(() => mixtureLR(NaN, 1e-6, 0.01)).toThrow();
    expect(() => mixtureLR(0.1, Infinity, 0.01)).toThrow();
    expect(() => mixtureLR(0.1, 1e-6, NaN)).toThrow();
  });

  it("agrees with the Python fixture to 1e-12 (scalar cases)", () => {
    expect(fixture.lr_cases.length).toBeGreaterThanOrEqual(20);
    for (const c of fixture.lr_cases) expectClose(mixtureLR(c.diff, c.var_diff, c.tau), c.lr, `LR(${c.diff}, ${c.var_diff}, ${c.tau})`);
  });
});

describe("alwaysValidP", () => {
  it("is non-increasing, within (0, 1] and equals min(1, 1 / running max Λ)", () => {
    const rnd = mulberry32(3);
    const lrs: number[] = [];
    for (let i = 0; i < 500; i++) lrs.push(Math.exp(4 * (rnd() - 0.5) * 2));
    const p = alwaysValidP(lrs);
    expect(p.length).toBe(lrs.length);
    let running = 0;
    for (let k = 0; k < lrs.length; k++) {
      running = Math.max(running, lrs[k]!);
      expectClose(p[k]!, Math.min(1, 1 / running), `p[${k}]`);
      expect(p[k]!).toBeGreaterThan(0);
      expect(p[k]!).toBeLessThanOrEqual(1);
      if (k > 0) expect(p[k]!).toBeLessThanOrEqual(p[k - 1]!);
    }
    expect(alwaysValidP([])).toEqual([]);
    expect(alwaysValidP([0, 0.5, 1])).toEqual([1, 1, 1]);
    expect(alwaysValidP([0, 4, 2, Infinity])).toEqual([1, 0.25, 0.25, 0]);
    expect(() => alwaysValidP([1, -0.1])).toThrow();
    expect(() => alwaysValidP([NaN])).toThrow();
    expect(fixture.always_valid_p_cases.length).toBeGreaterThanOrEqual(3);
    for (const c of fixture.always_valid_p_cases) {
      const got = alwaysValidP(c.lrs);
      expect(got.length).toBe(c.p.length);
      c.p.forEach((v, k) => expectClose(got[k]!, v, `fixture p[${k}] of ${JSON.stringify(c.lrs)}`));
    }
  });
});

describe("tauFromMde", () => {
  it("uses the planned absolute MDE (magnitude) and rejects zero or non-finite input", () => {
    expect(tauFromMde(0.01)).toBe(0.01);
    expect(tauFromMde(-0.01)).toBe(0.01);
    expectClose(tauFromMde(0.1 * 0.1), 0.01, "10% baseline, +10% relative");
    expect(() => tauFromMde(0)).toThrow();
    expect(() => tauFromMde(NaN)).toThrow();
    expect(() => tauFromMde(Infinity)).toThrow();
    for (const c of fixture.tau_cases) expectClose(tauFromMde(c.mde_abs), c.tau, `tau(${c.mde_abs})`);
  });
});

describe("msprtSeries", () => {
  it("reproduces the Python cumulative proportion cases (lr, always-valid p, decision look)", () => {
    expect(fixture.proportion_cases.length).toBeGreaterThanOrEqual(4);
    for (const c of fixture.proportion_cases) {
      const looks = c.n_a.length;
      const points: SeqPoint[] = [];
      for (let k = 0; k < looks; k++) points.push(proportionPoint(c.conv_a[k]!, c.n_a[k]!, c.conv_b[k]!, c.n_b[k]!));
      const baseline = c.conv_a[looks - 1]! / c.n_a[looks - 1]!;
      const tau = c.tau ?? tauFromMde(baseline * (c.mde_rel ?? 0.05));
      expectClose(tau, c.expected.tau, `${c.name}: tau`);
      expectSeries(msprtSeries(points, tau, c.alpha), c.expected, c.name);
    }
    // the first proportion case decides at look 4 of 5 at alpha 0.05, at look 5 at alpha 0.01 and never at alpha 1e-4
    const first = fixture.proportion_cases[0]!;
    const pts = first.n_a.map((n, k) => proportionPoint(first.conv_a[k]!, n, first.conv_b[k]!, first.n_b[k]!));
    expect(msprtSeries(pts, 0.02, 0.05).decidedAt).toBe(4);
    expect(msprtSeries(pts, 0.02, 0.01).decidedAt).toBe(5);
    expect(msprtSeries(pts, 0.02, 1e-4).decidedAt).toBeNull();
  });

  it("reproduces the Python mean cases through meanPoint (Welch variance of the difference)", () => {
    expect(fixture.mean_cases.length).toBeGreaterThanOrEqual(2);
    for (const c of fixture.mean_cases) {
      const points = c.a.map((row, k) => meanPoint(row, c.b[k]!));
      expectSeries(msprtSeries(points, c.tau, c.alpha), c.expected, c.name);
    }
    const p = meanPoint({ n: 200, mean: 10, var: 4 }, { n: 200, mean: 10.4, var: 4.5 });
    expectClose(p.diff, 0.4, "meanPoint diff");
    expectClose(p.varDiff, 4 / 200 + 4.5 / 200, "meanPoint varDiff");
    expect(() => meanPoint({ n: 1, mean: 10, var: 4 }, { n: 200, mean: 10.4, var: 4.5 })).toThrow();
    expect(() => meanPoint({ n: 200, mean: 10, var: -4 }, { n: 200, mean: 10.4, var: 4.5 })).toThrow();
  });

  it("validates its inputs and treats looks without users as no evidence", () => {
    const pts = [proportionPoint(95, 1000, 110, 1000), proportionPoint(205, 2000, 230, 2000)];
    expect(() => msprtSeries(pts, 0)).toThrow();
    expect(() => msprtSeries(pts, -0.01)).toThrow();
    expect(() => msprtSeries(pts, NaN)).toThrow();
    expect(() => msprtSeries(pts, 0.02, 0)).toThrow();
    expect(() => msprtSeries(pts, 0.02, 1)).toThrow();
    expect(() => msprtSeries([{ diff: 0.1, varDiff: -1 }], 0.02)).toThrow();
    expect(() => msprtSeries([{ diff: NaN, varDiff: 1 }], 0.02)).toThrow();
    expect(msprtSeries([], 0.02)).toEqual({ lr: [], pAV: [], decidedAt: null });
    expect(proportionPoint(0, 0, 0, 0)).toEqual({ diff: 0, varDiff: 0 });
    expect(proportionPoint(0, 0, 3, 10)).toEqual({ diff: 0, varDiff: 0 });
    expect(() => proportionPoint(11, 10, 3, 10)).toThrow();
    expect(() => proportionPoint(-1, 10, 3, 10)).toThrow();
    const flat = msprtSeries([{ diff: 0, varDiff: 1e-4 }, { diff: 0, varDiff: 5e-5 }], 0.01);
    expect(flat.pAV).toEqual([1, 1]);
    expect(flat.decidedAt).toBeNull();
    const withGap = msprtSeries([proportionPoint(0, 0, 0, 0), ...pts, proportionPoint(310, 3000, 370, 3000), proportionPoint(405, 4000, 500, 4000)], 0.02);
    expect(withGap.lr[0]).toBe(0);
    expect(withGap.pAV[0]).toBe(1);
    expect(withGap.decidedAt).toBe(5); // 1-based, counting the empty first look
  });

  it("legal peeking: the any-look false-positive rate of an A/A test stays at alpha while the naive rule does not", () => {
    const sims = 400, looks = 20, perLook = 2000, alpha = 0.05, rate = 0.1;
    const tau = tauFromMde(rate * 0.1);
    const rnd = mulberry32(20261);
    const zc = normPpf(1 - alpha / 2);
    let sequentialHits = 0, naiveHits = 0;
    for (let s = 0; s < sims; s++) {
      let cA = 0, cB = 0, n = 0, naive = false;
      const points: SeqPoint[] = [];
      for (let k = 0; k < looks; k++) {
        cA += binomial(perLook, rate, rnd);
        cB += binomial(perLook, rate, rnd);
        n += perLook;
        const pt = proportionPoint(cA, n, cB, n);
        points.push(pt);
        if (Math.abs(pt.diff) / Math.sqrt(pt.varDiff) > zc) naive = true;
      }
      if (msprtSeries(points, tau, alpha).decidedAt !== null) sequentialHits++;
      if (naive) naiveHits++;
    }
    const fpr = sequentialHits / sims, se = Math.sqrt((alpha * (1 - alpha)) / sims);
    expect(fpr).toBeLessThanOrEqual(alpha + 3 * se);
    expect(naiveHits / sims).toBeGreaterThan(0.1);
    expect(fpr).toBeLessThan(naiveHits / sims);
  });

  it("has power ≥ 0.8 at full sample when the true effect equals tau", () => {
    const sims = 400, looks = 20, perLook = 2000, alpha = 0.05;
    const tau = tauFromMde(0.01);
    const rnd = mulberry32(20262);
    let decided = 0, lastLook = 0;
    for (let s = 0; s < sims; s++) {
      let cA = 0, cB = 0, n = 0;
      const points: SeqPoint[] = [];
      for (let k = 0; k < looks; k++) {
        cA += binomial(perLook, 0.1, rnd);
        cB += binomial(perLook, 0.11, rnd);
        n += perLook;
        points.push(proportionPoint(cA, n, cB, n));
      }
      const d = msprtSeries(points, tau, alpha).decidedAt;
      if (d !== null) { decided++; if (d === looks) lastLook++; }
    }
    expect(decided / sims).toBeGreaterThanOrEqual(0.8);
    expect(lastLook).toBeLessThan(decided); // most decisions arrive before the final look
  });
});
